version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 5000:5000

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
